"""Experimental deep-learning portability for spherical PanorAi operators.

The namespace is explicit opt-in and requires Torch. It combines reusable ERP
spherical operators with adapters that preserve pretrained classifier
parameters while changing their topology and sampling domain.
"""

from panorai.image_processing.torch import (
    SPHERICAL_TORCH_CONVOLUTION_INTERFACE,
    PortedLayer,
    SphericalAvgPool2d,
    SphericalConv2d,
    SphericalConvTranspose2d,
    SphericalMaxPool2d,
    SphericalPortReport,
    port_module,
    port_module_with_report,
    spherical_area_average,
)

from .fcn import DenseFCNOutput, ImageNetFCN, class_activation_map
from .classification import (
    SPHERICAL_CLASSIFICATION_INTERFACE,
    OPENCLIP_REPOSITORY_REVISION,
    OPENCLIP_RN50_OPENAI,
    PLACES365_CATEGORIES,
    PLACES365_RESNET18,
    PLACES365_SOURCE_COMMIT,
    ClassificationArtifactRecord,
    ClassificationArtifactSpec,
    ClassificationTermsNotAcceptedError,
    DenseOpenVocabularyOutput,
    LoadedOpenCLIPRN50,
    LoadedPlaces365Model,
    OpenCLIPAssets,
    OpenCLIPRN50Dense,
    Places365Assets,
    Places365ResNet18FCN,
    acquire_openclip_rn50,
    acquire_places365_resnet18,
    encode_openclip_prompts,
    load_openclip_rn50,
    load_places365_resnet18,
)
from .depth import (
    SPHERICAL_METRIC_DEPTH_INTERFACE,
    METRIC3D_CHECKPOINT_REVISION,
    METRIC3D_CONVNEXT_TINY_V1,
    METRIC3D_SOURCE,
    METRIC3D_SOURCE_COMMIT,
    ExternalArtifactRecord,
    ExternalArtifactSpec,
    LoadedSphericalDepthModel,
    Metric3DAssets,
    SphericalMetric3D,
    UpstreamTermsNotAcceptedError,
    acquire_metric3d_convnext_tiny_v1,
    load_spherical_metric3d_convnext_tiny_v1,
)
from .pretrained import (
    SUPPORTED_IMAGENET_MODELS,
    ImageNetWeightRecord,
    LoadedImageNetModel,
    load_pretrained_imagenet_model,
    prefetch_imagenet_weights,
)

sphericalize = port_module

__all__ = [
    "SPHERICAL_TORCH_CONVOLUTION_INTERFACE",
    "SPHERICAL_METRIC_DEPTH_INTERFACE",
    "SPHERICAL_CLASSIFICATION_INTERFACE",
    "OPENCLIP_REPOSITORY_REVISION",
    "OPENCLIP_RN50_OPENAI",
    "PLACES365_CATEGORIES",
    "PLACES365_RESNET18",
    "PLACES365_SOURCE_COMMIT",
    "ClassificationArtifactRecord",
    "ClassificationArtifactSpec",
    "ClassificationTermsNotAcceptedError",
    "DenseFCNOutput",
    "DenseOpenVocabularyOutput",
    "ImageNetFCN",
    "ImageNetWeightRecord",
    "ExternalArtifactRecord",
    "ExternalArtifactSpec",
    "LoadedSphericalDepthModel",
    "LoadedImageNetModel",
    "LoadedOpenCLIPRN50",
    "LoadedPlaces365Model",
    "PortedLayer",
    "METRIC3D_CHECKPOINT_REVISION",
    "METRIC3D_CONVNEXT_TINY_V1",
    "METRIC3D_SOURCE",
    "METRIC3D_SOURCE_COMMIT",
    "Metric3DAssets",
    "OpenCLIPAssets",
    "OpenCLIPRN50Dense",
    "Places365Assets",
    "Places365ResNet18FCN",
    "SphericalAvgPool2d",
    "SphericalConv2d",
    "SphericalConvTranspose2d",
    "SphericalMetric3D",
    "SphericalMaxPool2d",
    "SphericalPortReport",
    "SUPPORTED_IMAGENET_MODELS",
    "UpstreamTermsNotAcceptedError",
    "acquire_metric3d_convnext_tiny_v1",
    "acquire_openclip_rn50",
    "acquire_places365_resnet18",
    "class_activation_map",
    "encode_openclip_prompts",
    "load_pretrained_imagenet_model",
    "load_openclip_rn50",
    "load_places365_resnet18",
    "load_spherical_metric3d_convnext_tiny_v1",
    "port_module",
    "port_module_with_report",
    "prefetch_imagenet_weights",
    "spherical_area_average",
    "sphericalize",
]
