"""Experimental spherical semantic and panoptic segmentation.

The data contracts and pure mask utilities import without Torch.  Official
InternImage-G and SAM 2.1 assets remain external and are loaded lazily.
"""

from ._charts import (
    advance_chart,
    backproject_face_mask_sets,
    backproject_face_masks,
    extract_mask_face,
    extract_rgb_face,
    face_point_direction,
)
from ._fusion import (
    merge_proposals,
    non_maximum_suppression,
    partition_proposals_by_origin,
    proposal_is_accepted,
    resolve_panoptic_map,
    semantic_support_for_mask,
    solid_angle_weights,
    weighted_containment,
    weighted_intersection_over_union,
)
from ._facade import (
    SPHERICAL_INDUSTRIAL_SEGMENTATION_INTERFACE,
    SphericalIndustrialSegmenter,
)
from ._models import (
    SPHERICAL_SEMANTIC_SEGMENTATION_INTERFACE,
    DenseSemanticEvidence,
    SemanticProxyConcept,
    SphericalBinaryMask,
    SphericalMaskProposal,
    SphericalSeed,
    SphericalSegment,
    SphericalSegmentationConfig,
    SphericalSegmentationResult,
)
from ._pipeline import SphericalSemanticSegmenter
from ._prompts import (
    SegmentPrompt,
    connected_component_at,
    consensus_frontiers,
    majority_and_envelope,
    mask_stability_score,
    maximum_pairwise_iou,
    pairwise_mask_iou,
    prompt_from_mask,
    prompt_grid,
)
from ._sam21 import (
    SAM21_HIERA_LARGE_LICENSE,
    SAM21_HIERA_LARGE_REPOSITORY,
    SAM21_HIERA_LARGE_REVISION,
    Sam21Assets,
    Sam21FileRecord,
    Sam21HieraLargeSegmenter,
    Sam21TermsNotAcceptedError,
    SamMultimaskOutput,
    acquire_sam21_hiera_large,
    load_sam21_hiera_large,
)
from ._semantic import (
    INDUSTRIAL_IMAGENET_PROXY_VOCABULARY,
    angular_distance_degrees,
    concept_display_names,
    concept_evidence_from_imagenet,
    concept_proxy_names,
    fibonacci_coverage_seeds,
    select_semantic_seeds,
)

__all__ = [
    "SPHERICAL_INDUSTRIAL_SEGMENTATION_INTERFACE",
    "SPHERICAL_SEMANTIC_SEGMENTATION_INTERFACE",
    "SAM21_HIERA_LARGE_LICENSE",
    "SAM21_HIERA_LARGE_REPOSITORY",
    "SAM21_HIERA_LARGE_REVISION",
    "INDUSTRIAL_IMAGENET_PROXY_VOCABULARY",
    "DenseSemanticEvidence",
    "Sam21Assets",
    "Sam21FileRecord",
    "Sam21HieraLargeSegmenter",
    "Sam21TermsNotAcceptedError",
    "SamMultimaskOutput",
    "SegmentPrompt",
    "SemanticProxyConcept",
    "SphericalBinaryMask",
    "SphericalIndustrialSegmenter",
    "SphericalMaskProposal",
    "SphericalSeed",
    "SphericalSegment",
    "SphericalSegmentationConfig",
    "SphericalSegmentationResult",
    "SphericalSemanticSegmenter",
    "acquire_sam21_hiera_large",
    "advance_chart",
    "backproject_face_mask_sets",
    "angular_distance_degrees",
    "backproject_face_masks",
    "concept_display_names",
    "concept_evidence_from_imagenet",
    "concept_proxy_names",
    "connected_component_at",
    "consensus_frontiers",
    "extract_mask_face",
    "extract_rgb_face",
    "face_point_direction",
    "fibonacci_coverage_seeds",
    "load_sam21_hiera_large",
    "majority_and_envelope",
    "mask_stability_score",
    "maximum_pairwise_iou",
    "merge_proposals",
    "non_maximum_suppression",
    "partition_proposals_by_origin",
    "pairwise_mask_iou",
    "prompt_from_mask",
    "prompt_grid",
    "proposal_is_accepted",
    "resolve_panoptic_map",
    "select_semantic_seeds",
    "semantic_support_for_mask",
    "solid_angle_weights",
    "weighted_containment",
    "weighted_intersection_over_union",
]
