# Minimal Sphinx documentation build Makefile

SPHINXBUILD   = sphinx-build
SPHINXOPTS    =
SOURCEDIR     = .
BUILDDIR      = _build

.PHONY: html
html:
	$(SPHINXBUILD) -b html $(SOURCEDIR) $(BUILDDIR)/html $(SPHINXOPTS)
